# Action to compare if the latest version,
# if not, push commit and build
---
name: compare release

on:
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  compare-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      committed: ${{ steps.commit.outputs.committed }}
      commit_long_sha: ${{ steps.commit.outputs.commit_long_sha }}

    steps:
      - name: Checkout repo
        id: checkout-repo
        uses: actions/checkout@v4

      - name: compare
        id: compare
        run: |
          sudo apt update \
            && sudo apt install -y quilt
          .github/workflows/scripts/compare-release.sh

      - name: commit
        id: commit
        if: ${{ steps.compare.outputs.sha256 != '' }}
        uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          default_author: github_actions

  build-openwrt-images:
    needs: compare-release
    if: ${{ needs.compare-release.outputs.committed == 'true' }}
    uses: ./.github/workflows/build.yml
    with:
      commit_long_sha: ${{ needs.compare-release.outputs.commit_long_sha }}
